os:
- linux
language: node_js
node_js:
- 10.1.0
branches:
  only:
  - master
script:
- echo "Deploying..."
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "FhHezdmRDXZtJVUKv/HsFQhL5lvvCKuPpw9FVPYhIgf7eoHs2ymxEZe8Ecchdk5h7GBR1HFZAdn+NEFzM2prY82pB5zK5+tUeyolR3HKf5lAWYfSPBNkzlnMQX1reZ9Wq5QYmDqH8XIJeBY5m9XSItat390sfe/JlIe8ngYR5KnaYEe/Nd4LAyqM4VQ2K/dz0uPrfdDlGSib5OFRJykx5IvdskctSbBl494DbCrKmbAgSjK2lqoig5bDKiJk9oKaEYjIucAe0TK7cMHQ1uy17eSz3cZ5JSiPL70BgzJAEq+BSr7NCYjIuyHbyQgQMsptBjarqETUNhzH38sioAQcWDOhvPCeC3kyn9zS+/BF6U/PIBUwlEvov0ISyjvWwFTXQo1PbDJAZb7gAFgNzlOEY4TD1VPiewzePNsNeZCjJBiwFTVzswNzBrvO2CLUQZnDSHNNP3rzVoKl13bIEMNc69VcAOAXqat5p0rrFcgwsh+1aysqx/SNSiQSvW3ySUI6N0uTc3jCjII08qPTwreGLC4OBHuV8yRR6dZe24bhRpPIAQBjytFTZ6Pwtbey0hX9FMSbIV5L6gCVkxYyigiMLZBNp48gWqQvgeC870erQ/ZxsC8JTmIL3FUhzb85ns4eJK+cep3gGAOGyKdva3Z3+62zz8rc6BMBKX13KNMUDaQ="
