os:
- linux
language: node_js
node_js:
- 10
branches:
  only:
  - master
script:
- echo 0
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
deploy:
  provider: firebase
  edge: true
  token:
    secure: 
"dW7/8kBE0yZjcNXZh7LNWVx2ZKQqmJHCuTANa7acNUr2+fx4y44KCiqCS2T0w2GRCYNqQIahcdXnTH9wNNCNadc9FEq5qkVM0BRPJGQ60TSyxf/NlNA7UqL7kXangUnU2aC5n5BbE7W1+CPjF8YwPLylqoc9SXf/aEKkLjNTRPvTEukATr/S7osgzccUtlLJmMa7r5uV7fnyfaKlwnQfNE/hIX+GSS/gY80zfzDm1xaeSXGWM5oz8cZWjw5ApqsaloHfM5gpjekFVVaQxiPm5WdW1ckpy55HWmVwSTLi2PwIcQT4VF+qYkz2aXw8ecxweHA/ZSC0xl2Thygv8JQseHG1CVkEa+gjc9Reyrwgqoj2uG+IQeGjq9eOzL3TpT/OxYUeXPRhAjpkhDSbFXWT13iZ08xpx1PAsJteJDs/pWkm7YFNMsz3+ZC/QSoN7Frxgfd3/8hl+Aa5jLcU755CVNOVwXSm/PV7tPRTb+kHmzCiVdOotynynQUWN6OjlF3Pxyo6z7yqLWwV8tgPaqA+LkPO5wrj1HvY6yt3r6UkCIIPvUQ1v79CjQGdM+n3hyNpo4oe4rOU8g5i53gNnRz/SKyLvYSxfK9FC9Ic/gWvO6b99+IWAvmdywJF58ZFB+WzP4bKoSkGvcDraD3XtWYfa9YdH4NRk21yBX/SZ7r+Igs="
  message: "$TRAVIS_COMMIT_MESSAGE"
