os:
- linux
language: node_js
node_js:
- 10.1.0
branches:
  only:
  - master
script:
  - "./deploy.sh"
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
# deploy:
#  provider: firebase
#  token:
#    secure: "QzCb6D/S46DDczY575S1tm6h1UYhFV8Oei8awzCVSaBumDkAynEEQFTI0mi/kKW24C0GSPOhhZdYWpM6Nrq9/s29UznwtWCpY1qt1BF+tupphqr/QpJ+of6sH1pQW/plicNg1KFKbdutGPCBJJs1lcE02I8D+My9b+2jneoF+E/zvY7tnE6kLzDLivDR/Dz/e0RGwVuH5paISD4Rh/HOME3DqNg4bOeIePWvCGt9IoVIcFXQvVOdiSse6sSNHWuoAbZcBaXfL4XH4MrOqb5Df1GPjQ8hxWSL0srGqVVT4h8y/nt0K97qd6xGgBciWLzkmZXBHXcG1isFFTwVUZ9NMUPr/VaMZWX3LIo1v4sdyuoXusAuZNRX3zuj/3QfZNWFP667vlVM63CXo2acDsMFCOs1mcgzE/Xf0PcYP70Zc8sql/vhZ8rnmpgPVgANRWl9K1BklxXlkMlGCqWdBDg/BKBE2+9gVgYzy5LLhRmnTp7tHjJWmYCzXcBDzxjnV+d3zcixOnnL122J8ic6x0GwQwfI0hFPGpPQGwDwn3svi3BrfY3S1HJLPnWO3bC8cW/uO54bgJ8J2IDF3p8txuXntCj7MGDzRIrBraLmKgB9sO/NB2Er2S5dGlhJ1lLvc+ylQWpHBOmApuqp0EPeA3sZuPrbrazQELNSR97Zco02JuI="
